[package]
name = "uncompress"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#sevenz-rust = { path = "../../sevenz-rust" }
sevenz-rust = "0.6.1"