[package]
name = "metadata"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.155", features = ["derive"] }
time = { version = "0.3.20", features = ["serde"] }
serde_json = "1.0.94"
