[package]
name = "metadata"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.180", features = ["derive"] }
time = { version = "0.3.25", features = ["serde"] }
serde_json = "1.0.104"
