[package]
name = "clap_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.51"
exitcode = "1.1.2"

[dev-dependencies]
assert_cmd = "2.1.0"