name: release-selenium-manager

on: workflow_dispatch

jobs:
  macos:
    name: "[macOS] Build selenium-manager"
    runs-on: macos-latest
    steps:
      - name: "Checkout project"
        uses: actions/checkout@master
      - name: "Update Rust"
        run: rustup update stable
      - name: "Build release"
        run: |
          cd selenium-manager
          cargo build --release
      - name: "Upload binary"
        uses: actions/upload-artifact@v3
        with:
          name: selenium-manager-macos-amd64
          path: ./target/release/selenium-manager
          retention-days: 6

  linux:
    name: "[Linux] Build selenium-manager"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout project"
        uses: actions/checkout@master
      - name: "Install dependencies"
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install -y pkg-config libssl-dev
      - name: "Update Rust"
        run: rustup update stable
      - name: "Build release"
        run: |
          cd selenium-manager
          cargo build --release
      - name: "Upload binary"
        uses: actions/upload-artifact@v3
        with:
          name: selenium-manager-linux-amd64
          path: ./target/release/selenium-manager
          retention-days: 6

  windows:
    name: "[Windows] Build selenium-manager"
    runs-on: windows-latest
    steps:
      - name: "Checkout project"
        uses: actions/checkout@master
      - name: "Update Rust"
        run: rustup update stable
      - name: "Build release"
        run: |
          cd selenium-manager
          cargo build --release
      - name: "Upload release"
        uses: actions/upload-artifact@v3
        with:
          name: selenium-manager-windows-amd64
          path: ./target/release/selenium-manager.exe
          retention-days: 6